# Use the official Python image as a base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8501 (default port for Streamlit)
EXPOSE 8501

# Command to run Streamlit when the container starts
CMD ["streamlit", "run", "Weather_App_V2.py"]
